# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dice Roller 2000
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Dice Roller 2000 is a random number generator which can be used in roleplaying games like D&D or Shadowrun. 
  Designed for the situations where you need to roll lots of dices at the same time. 
  Some options can be provided to the rolls, like mark the successful or the failed rolls.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://theaspen.github.io/Dice_Roller_2000/ # the base hostname & protocol for your site, e.g. http://example.com
github_username:  TheAspen
github_url: https://github.com/TheAspen/Dice_Roller_2000
license: Dice Roller 2000 is under the [MIT-license](https://github.com/TheAspen/Dice_Roller_2000/blob/5fb63caaf5eb1a318877b4bf1e24432ba320db63/README.txt).

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
